# Local Development Override
# Use this when XAMPP is running and you want to use a different port
# Or use this for local dev with HTTP-only config (no SSL)
# Usage: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d

services:
  frontend:
    build:
      dockerfile: Dockerfile.local  # Use HTTP-only nginx config
    ports:
      - "3000:80"  # Access at http://localhost:3000 instead of http://localhost
      # Remove 443 for local dev (no SSL needed)
      # - "443:443"
    volumes:
      # Remove SSL certificate volumes for local dev
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      # - /var/www/certbot:/var/www/certbot:ro

